### ISSUE TITLE
Add possibility to donate in Bitcoin

### ISSUE THREAD

**Issue by ghost** [babydots/babydots#33]
Hi, we have just started to use the app and our baby loves it!

However as un-banked person, I cannot donate dirty fiat, so I ask you to consider adding Bitcoin donations (Lightning Network is needed because of low transaction fees).

The easysiest solution is to use https://btcpayserver.org/ (it is de-facto market standard and it supports Lightning Network).

**Comment by pserwylo** [comment]
Thank you for the kind comments and the offer of donations. 

In the long term, I'd love to investigate allowing people to donate to my open source efforts via Bitcoin. However at this point in time, it is more than enough just to hear that our little app is helping your baby :)
