### ISSUE TITLE
Blocked texts on the about page

### ISSUE THREAD

**Issue by EasyVector** [babydots/babydots#42]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the about page, **the last part of texts could not be seen fully, and this page is not scrollable also**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.5.0, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts on the about page, and in this circumstance, part of them seem to be blocked. 

**Steps to reproduce the behavior:**

1. use the largest font and display in the display setting
2. click the three vertical dots at the top-right of the main page(with lots of dots on it)
3. click the about button
4. this error could be seen

**Screenshot**

(The blocked part is marked in red rectangular)

<img src="https://user-images.githubusercontent.com/25502419/131315024-21e0edd2-13d3-47d1-bbbb-d09f15639848.png" alt="copy" width="250"/>

**Environment**

1. Version of babydots: 1.5.0
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by pserwylo** [comment]
Thank you very much for this exceptionally detailed report. I really appreciate the description of the issue, the proposed solution, the annotated screenshots, and the details of your device. Furthermore, it is even better in that it came with a PR to fix it! Merged, so will close this and bump a new version. That will be released to F-Droid in the next week or so, then Google Play.
