### ISSUE TITLE
“Canon in D” was composed by Pachelbel, not Bach

### ISSUE THREAD

**Issue by Quoor8ee** [babydots/babydots#64]
[“The Canon”](https://en.wikipedia.org/wiki/Pachelbel%27s_Canon), is one of the most notorious Baroque-era pieces, inevitable for anyone into ensemble music. However, it is not written by J. S. Bach (or anyone else of the Bach family), but rather by his contemporary Johann Pachelbel.

Not entirely sure whom to blame for that mistake; it seems that [Kevin MacLeod](https://freemusicarchive.org/music/Kevin_MacLeod/Classical_Sampler) has put it in between several Bach pieces, yet he avoided to mention either of Bach or Pachelbel.

I've seen that this wrong attribution has also found its way into the translations. So, unfortunately, no one-click solution to fix this. Should I open a pull request?

**Comment by pserwylo** [comment]
Haha, yes please, a pull request would be very welcome. Thanks for the detailed explanation too. As for translations, perhaps feel free to choose whether or not to update any of the translations based on whether or not the translators have localised any of the composers. If so, leave it and the Weblate system will notify those translators of the change when itis made to the English source string.

Thanks!

**Comment by pserwylo** [comment]
Whoops, forgot to tag a release. Tagged [v1.9.3](https://github.com/babydots/babydots/releases/tag/v1.9.3) now to be built and released by F-Droid in the coming days (perhaps a week). Thanks again :)
